sonar.projectKey=sonar-react-app
sonar.host.url=http://3.27.16.121:9000
sonar.login=admin
sonar.sources=src
sonar.tests=src/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8