sonar.projectKey=sonar-react-app-dev
sonar.projectName=sonar-react-app-dev
sonar.projectVersion=1.0
sonar.host.url=http://3.27.16.121:9000
sonar.login=admin
sonar.sources=src
#sonar.tests=src
sonar.inclusions=src/App.js
sonar.test.inclusions=src/App.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8